### ISSUE TITLE
Version 1.2.1 doesnt work anymore?

### ISSUE THREAD

**Issue by raindeer** [krokedil/klarna-onsite-messaging-for-woocommerce#23]
When the on site messaging script is included like this is doesnt work:
```
<script async src='https://eu-library.klarnaservices.com/lib.js?ver=1.2.1' data-client-id="xxx"></script>
```
However, if I remove "?ver=1.2.1" it starts working again.

What is going on?

**Comment by MichaelBengtsson** [comment]
This was a issue due to a change from Klarnas side. It was fixed by them shortly after the issue, but will also be completely solved by us in the next version since we are removing the version number from the script completely. If you are still having an issue with this, then please reopen the issue.
